[package]
name = "cargo-license"
description = "Cargo subcommand to see license of dependencies"
authors = ["Onur Aslan <onur@onur.im>"]
version = "0.1.6"
license = "MIT"
readme = "README.md"
repository = "https://github.com/onur/cargo-license"

[dependencies]
cargo = "0.19"
error-chain = "0.10"
getopts = "0.2.14"
toml = "0.2"
ansi_term = "0.9"

[[bin]]
name = "cargo-license"
path = "src/cargo-license.rs"
